apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: runbooks.runbookpublishing.kubeops.dev
spec:
  group: runbookpublishing.kubeops.dev
  names:
    kind: runbook
    listKind: runbookList
    plural: runbooks
    singular: runbook
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              runbookStatus:
                type: string
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              document:
                type: string
              identifier:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}